version: 2.1

jobs:
  test-user-namespaces:
    machine:
      image: ubuntu-2204:current  # Full VM with more privileges than docker executor
    steps:
      - checkout

      - run:
          name: Install Nix
          command: |
            curl -L https://nixos.org/nix/install | sh
            . ~/.nix-profile/etc/profile.d/nix.sh

      - run:
          name: Check if unprivileged user namespaces are supported
          command: |
            set -e
            echo "Checking unshare user namespace:"
            if unshare --user --mount echo "✅ Unprivileged user namespaces work"; then
              echo "You can run buildFHSUserEnv here."
            else
              echo "❌ Unprivileged user namespaces are not available."
              exit 1
            fi
