version: 2.1

setup: true

orbs:
  path-filtering: circleci/path-filtering@2.0.1

workflows:
  setup-workflow:
    jobs:
      - path-filtering/filter:
          base-revision: main
          config-path: .circleci/noop.yml
          mapping: |
            templates/fhs/.* .circleci/test.yml
            includes/.* .circleci/test.yml
            copier.yml .circleci/test.yml
