version: 2.1

executors:
  nix-machine:
    machine:
      image: ubuntu-2204:current
    working_directory: ~/repo

jobs:
  setup:
    executor: nix-machine
    steps:
      - checkout

      - run:
          name: Install Nix
          command: |
            curl -L https://nixos.org/nix/install | sh
            . ~/.nix-profile/etc/profile.d/nix.sh

      - run:
          name: Install Copier
          command: |
            . ~/.nix-profile/etc/profile.d/nix.sh
            nix profile install nixpkgs#copier

      - run:
          name: Generate default answers.yml
          command: |
            cat <<EOF > answers.yml
            codeserver: false
            cudaSupport: false
            framework: fhs
            i_know_what_i_am_doing: false
            python_package_manager: pixi
            python_version: "3.11"
            shell: bash
            EOF

      - run:
          name: Run copier to scaffold project
          command: |
            . ~/.nix-profile/etc/profile.d/nix.sh
            copier copy --force --trust --data-file answers.yml . generated/

      - run:
          name: Generate flake.lock
          command: |
            . ~/.nix-profile/etc/profile.d/nix.sh
            cd generated && nix flake lock

      - persist_to_workspace:
          root: generated
          paths:
            - flake.lock

  test:
    executor: nix-machine
    parameters:
      package_manager: [pixi, micromamba, uv]
      shell: [zsh]
      python_version: ["3.10"]
    steps:
      - checkout

      - attach_workspace:
          at: ~/repo/generated

      - run:
          name: Install Nix
          command: |
            curl -L https://nixos.org/nix/install | sh
            . ~/.nix-profile/etc/profile.d/nix.sh

      - run:
          name: Install Copier
          command: |
            . ~/.nix-profile/etc/profile.d/nix.sh
            nix profile install nixpkgs#copier

      - run:
          name: Generate answers.yml
          command: |
            cat <<EOF > answers.yml
            codeserver: false
            cudaSupport: false
            framework: fhs
            i_know_what_i_am_doing: false
            declarative_python_environment: true
            python_packages: numpy
            python_package_manager: << parameters.package_manager >>
            python_version: << parameters.python_version >>
            shell: << parameters.shell >>
            EOF

      - run:
          name: Run Copier
          command: |
            . ~/.nix-profile/etc/profile.d/nix.sh
            copier copy --force --trust --data-file answers.yml . generated/

      - run:
          name: Use shared flake.lock
          command: |
            cp ~/repo/generated/flake.lock generated/

      - run:
          name: Test with nix develop
          command: |
            . ~/.nix-profile/etc/profile.d/nix.sh
            cd generated && nix run .# -- -c "python -c 'import numpy'"

workflows:
  version: 2
  test-template:
    triggers:
      - schedule:
          cron: "0 0 * * 1"
          filters:
            branches:
              only: main
    jobs:
      - setup
      - test:
          matrix:
            parameters:
              package_manager: [pixi, micromamba, uv]
              shell: [zsh]
              python_version: ["3.10"]
          requires:
            - setup
