version: 2.1

orbs:
  nix: eld/nix@1.1.1
  github-cli: circleci/github-cli@2.7.0
    
executors:
  nix-machine:
    machine:
      image: ubuntu-2204:current  # Full VM with more privileges than docker executor
    working_directory: ~/repo

parameters:
  run_tests:
    type: boolean
    default: false
 
jobs:
  test:
    executor: nix-machine
    parameters:
      package_manager: 
        type: enum
        default: pixi
        enum: [pixi, micromamba, uv]
      python_version:
        type: string
        default: "3.10"
      shell:
        type: enum
        default: zsh
        enum: [bash, zsh, fish]
    steps:
      - checkout

      - attach_workspace:
          at: ~/repo/generated

      - nix/install
      
      - run:
          name: Install Copier
          command: |
            nix profile add nixpkgs#copier
          

      - run:
          name: Generate answers.yml          
          command: |
            cat \<<EOF > answers.yml
            codeserver: false
            cudaSupport: false
            framework: fhs
            i_know_what_i_am_doing: false
            declarative_python_environment: true
            python_packages: numpy
            python_package_manager: << parameters.package_manager >>
            python_version: "<< parameters.python_version >>"
            shell: << parameters.shell >>
            stable: true
            EOF


      - run:
          name: Run Copier
          command: |
            copier copy --force --trust -r HEAD --data-file answers.yml . $PWD/generated/

      - run:
          name: Generate test.sh
          command: |
            cd generated
            cat \<<EOF > test.sh
            #!/usr/bin/env -S nix run --no-update-lock-file .# --

            echo "$(which python)"
            python --version
            
            python -c "import numpy" && echo "numpy import successful" || { echo "numpy import failed"; exit 1; }
            EOF
            chmod +x test.sh


      - run:
          name: Test with nix develop
          command: |
            cd generated
            git add flake.lock
            ./test.sh
          
  test-summary:
    docker:
      - image: cimg/base:stable
    steps:
      - run:
          name: Test summary
          command: |
            if [[ "<< pipeline.parameters.run_tests >>" == "false" ]]; then
              echo "Tests skipped due to path filtering."
            else
              echo "Tests were run and passed."
            fi
            exit 0

            
workflows:
  version: 2
  test-fhs-template:
    when: << pipeline.parameters.run_tests >>
    jobs:
      - test:
          matrix:
            parameters:
              package_manager: [pixi, micromamba, uv]
              python_version: ["3.11", "3.12", "3.13"]
              shell: ["bash", "zsh", "fish"]
      - test-summary:
          requires:
            - test
  skip-tests:
    when:
      not: << pipeline.parameters.run_tests >>
    jobs:
      - test-summary
