on:
  push:
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 1'  # every Monday at 00:00 UTC

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v27

      - name: Install Copier
        run: nix profile install nixpkgs#copier

      - name: Generate default answers.yml
        run: |
          cat <<-EOF > answers.yml
          codeserver: false
          cudaSupport: false
          framework: fhs
          i_know_what_i_am_doing: false
          python_package_manager: pixi
          python_version: "3.11"
          shell: bash
          EOF
      - name: Run copier to scaffold project
        run: copier copy --force --data-file answers.yml . generated/

      - name: Generate flake.lock
        working-directory: generated
        run: nix flake lock

      - name: Upload flake.lock
        uses: actions/upload-artifact@v4
        with:
          name: flake-lock
          path: generated/flake.lock
