on:
  push:
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 1'  # every Monday at 00:00 UTC

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        variant: [pixi, micromamba]
        shell: [zsh, bash, fish]
        python_version: [3.10, 3.11, 3.12, 3.13]

    steps:
      - uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v27

      - name: Install Copier
        run: nix profile install nixpkgs#copier

      - name: Generate answers.yml
        run: |
          case "${{ matrix.variant }}" in
            pixi)
              cat > answers.yml <<EOF
              codeserver: false
              cudaSupport: false
              declarative_python_environment: true
              framework: fhs
              i_know_what_i_am_doing: false
              isolated_environment: false
              project_name: myenv
              python_package_manager: pixi
              python_packages: ''
              python_version: '${{ matrix.python_version }}'
              shell: zsh
              EOF
              ;;
            *)
              echo "Unknown variant"
              exit 1
              ;;
          esac

      - name: Generate and test from template
        run: |
          copier copy --force --data-file answers.yml . generated/

          cd generated
          if [ -f flake.nix ]; then
            nix shell .# --command python --version
          else
            echo "No flake.nix found. Skipping."
          fi
