on:
  push:
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 1'  # every Monday at 00:00 UTC

jobs:
  setup:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4
  
        - name: Install Nix
          uses: DeterminateSystems/nix-installer-action@main
        - name: Install Copier
          run: nix profile install nixpkgs#copier
  
        - name: Generate default answers.yml
          run: |
            cat <<-EOF > answers.yml
            codeserver: false
            cudaSupport: false
            framework: fhs
            i_know_what_i_am_doing: false
            python_package_manager: pixi
            python_version: "3.11"
            shell: bash
            EOF
  
        - name: Run copier to scaffold project
          run: copier copy --force --trust --data-file answers.yml . generated/
  
        - name: Generate flake.lock
          working-directory: generated
          run: nix flake lock
  
        - name: Upload flake.lock
          uses: actions/upload-artifact@v4
          with:
            name: flake-lock
            path: generated/flake.lock

  test:
    needs: setup
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package_manager: [pixi, micromamba, uv]
        shell: [zsh]
        python_version: ["3.10"]

    steps:
      - uses: actions/checkout@v4
      
      - name: Download shared flake.lock
        uses: actions/download-artifact@v4
        with:
          name: flake-lock
          path: shared-lock

      - name: Install Nix
        uses: cachix/install-nix-action@v27

      - name: Install Copier
        run: nix profile install nixpkgs#copier

      - name: Generate answers.yml
        run: |
            cat <<-EOF > answers.yml
            codeserver: false
            cudaSupport: false
            framework: fhs
            i_know_what_i_am_doing: false
            declarative_python_environment: true
            python_packages: numpy
            python_package_manager: ${{ matrix.package_manager }}
            python_version: ${{ matrix.python_version }}
            shell: ${{ matrix.shell }}
            EOF
            
      - name: Run Copier
        run: copier copy --force --trust --data-file answers.yml . generated/

      - name: Use shared flake.lock
        run: cp shared-lock/flake.lock generated/

      - name: Generate test script
        working-directory: generated
        run: |
            cat <<-EOF > test.sh
            #!/usr/bin/env -S nix run .# --
            python --version
            python -c "import numpy"
            EOF
            chmod +x test.sh

      - name: Test with nix develop
        working-directory: generated
        run: |
          git add flake.lock
          ./test.sh
