on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'templates/devenv/**'
      - 'includes/**'
      - 'copier.yml'
  pull_request_target:
    paths:
      - 'templates/devenv/**'
      - 'includes/**'
      - 'copier.yml'

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package_manager: [uv]
        python_version: ["3.11", "3.12", "3.13"]

    steps:
      - name: Checkout PR code
        if: github.event_name == 'pull_request_target'
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}

      - name: Checkout main branch code
        if: github.event_name == 'push'
        uses: actions/checkout@v4
      
      - name: Install Nix
        uses: cachix/install-nix-action@v30
        with:
          extra_nix_config: |
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
      - name: Configure Cachix
        uses: cachix/cachix-action@v15
        with:
          name: devenv
      - name: Install devenv
        run: nix profile install nixpkgs#devenv

      - name: Install Copier
        run: nix profile install nixpkgs#copier

      - name: Generate answers.yml
        run: |
            cat <<-EOF > answers.yml
            codeserver: false
            cudaSupport: false
            framework: devenv
            i_know_what_i_am_doing: false
            declarative_python_environment: true
            python_packages: numpy
            python_package_manager: ${{ matrix.package_manager }}
            python_version: "${{ matrix.python_version }}"
            stable: true
            EOF
            
      - name: Run Copier
        run: copier copy --force --trust --data-file answers.yml . generated/

      - name: Test with devenv
        working-directory: generated
        run: |
          devenv shell "python -c 'import numpy' || EXIT 1"
